# Site settings
title: Dispatches from the Bubble
description: >
  I’m currently the Cloud and Platform Automation Manager at Kovarus. This blog
  is my way of contributing back to the community. It's also a sort of exposure
  therapy for my impostor syndrome. Maybe you’ll learn something. Better yet,
  maybe you’ll teach me something.
tagline: Random musings of an Op
baseurl: ""
url: "http://blog.danzil.io"
twitter_username: djdanzilio
github_username:  danzilio
disqus_shortname: danzilio
linkedin_shortname: djdanzilio
markdown: kramdown
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
paginate: 5
kramdown:
  input: GFM
timezone: Etc/UTC
mermaid-src: 'https://cdn.rawgit.com/knsv/mermaid/0.3.2/dist/mermaid.full.min.js'
